#!/usr/bin/env bash
# Bash script that displays:
while :                                            
do                                                 
        echo "To infinity and beyond"              
        sleep 2                                    
        trap 'echo "I am invincible!!!"' SIGTERM   
done

